<style type="text/css">
<!--
-->
</style>


<div id="content">
	<a href="/test_zf/handletest/paramName/paramValue">link to zf controller</a>

</div>


<?php 
echo $this->translate('language');
echo $this->translate('hello_world');


?>


<!--<script src="/js/jquery/ui/jquery.ui.datepicker.js" type="text/javascript"></script>-->
<script type="text/javascript">
<!--
$(document).ready(function(){
	$(function(){
		$('#today').datepicker({
			changeMonth: true,
			changeYear: true
		});
//		$('#today').datepicker();
	});
});
//-->
</script>
