<link href="/css/default/login/index.css" rel="stylesheet" type="text/css" />

<div id="container">
<form id="login">
<p id="tipsLogin"></p>
<p>email：<input name="email" id="email" type="text"></p>
<p>password：<input name="passwd" id="passwd" type="password"></p>
<p>
	<button id="btn_login" type="button">登陆</button>
	<button type="reset">重置</button>
</p>
</form>
</div>


<script src="/js/default/login/index.js" type="text/javascript"></script>
<script src="/js/util.js" type="text/javascript"></script>




