<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--  <title>CentOS</title>-->
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headLink()->appendStylesheet("/css/global.css"); ?>
	<?php echo $this->headStyle() ?>
	<?php echo $this->headScript() ?>
	<link href="/js/jquery/ui/themes/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />
	
	<script src="/js/jquery/jquery-1.6.2.js" type="text/javascript"></script>
	<script src="/js/jquery/ui/jquery-ui-1.8.16.custom.js" type="text/javascript"></script>
</head>
<body>
<div id="container">
<div id="header">
    <div id="header_logo"  style="float:left;">
    	<div>
	        <img alt="" src="/img/centos_icon_60.png"  />
	        <img alt="" src="/img/centos_logo_45.png" />
        </div>
        <div><img alt="" src="/img/centos_signature.png" /></div>
    </div>
    <div id="header_nav"  style="float:left; padding-top:70px;">
        <a href="/">Homepage</a>
        <a href="/phpinfo">Phpinfo</a>
        <a href="/test">Test</a>
    </div>
    <div id="header_crumb" style="clear:both;">
    	<?php 
    	$layout = Zend_Registry::get('LAYOUT');
    	if (isset($layout->crumbs)):
    	?>
        <a href="/">首页</a>
        <?php for ($i = 0; $i < count($layout->crumbs); $i++):?>
        	<?php if ($i == count($layout->crumbs)-1):?>
        	 &gt; <?=$layout->crumbs[$i]['name']?>
        	<?php else:?>
        	 &gt; <a href="<?=$layout->crumbs[$i]['uri']?>"><?=$layout->crumbs[$i]['name']?></a>
        	<?php endif;?>
        <?php endfor;?>
        <?php endif;?>
    </div>
</div>
<div style="clear:both;"></div>
<?php echo $this->layout()->content ?>

</div>
</body>
</html>